feat: install new devDeps
Dimetio/react-burger pull request #8
Opened 2023-01-01 18:13 UTC by Dimetio

2023-01-11 16:08 UTC, andryxxa93 requested changes
Всё отлично. Сокет соединения настроены верно. Проект соответствует требованиям брифа. Есть только одно замечание:
- Сокет соединение должно открываться при открытии именно "Истории заказов" а не просто страницы профиля. И соответственно закрываться тоже должно при уходе с этой страницы сразу же. 
Исправьте этот момент и ваша работа будет принята!

2023-01-11 16:08 UTC, andryxxa93 commented on src/components/app/app.tsx
> +  const user = useSelector((store) => store.auth.user);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-01-11 19:53 UTC, Dimetio commented on src/components/app/app.tsx
> +  const user = useSelector((store) => store.auth.user);
а как в таком случае быть с типизацией?

2023-01-12 06:13 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

2023-01-17 11:45 UTC, merged